trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm test
    displayName: 'Install dependencies and run tests'
  - script: |
      zip -r app.zip .
    displayName: 'Package application'
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/app.zip'
      ArtifactName: 'drop'
    displayName: 'Publish Artifact'

  # Lisää tähän vaihe sovelluksen pakkaamiseksi zip-muotoon
  # Lisää tähän vaihe artefaktin julkaisemiseksi nimellä drop
